import { page, esc, breadcrumbs, breadcrumbJsonLd, adSlot, SITE, AUTHOR } from '../layout.mjs';
import { COUNT_BY_TYPE } from '../data/index.mjs';
import { FAQS } from './home.mjs';

const UPDATED = '27 August 2026';

function prosePage(opts) {
  const crumbs = [{ href: '/', label: 'Home' }, { href: opts.path, label: opts.crumb }];
  const body = [
    '<section class="hero hero--compact">',
    '<div class="hero__blobs" aria-hidden="true"><span class="hero__blob hero__blob--a"></span><span class="hero__blob hero__blob--b"></span></div>',
    '<div class="container hero__inner">',
    breadcrumbs(crumbs),
    '<h1>' + esc(opts.h1) + '</h1>',
    opts.lede ? '<p class="hero__lede">' + esc(opts.lede) + '</p>' : '',
    '</div>',
    '</section>',
    '<section class="section">',
    '<div class="container">',
    '<div class="prose">',
    opts.updated ? '<p class="prose__meta">Last updated: ' + UPDATED + '</p>' : '',
    opts.content,
    '</div>',
    adSlot('display'),
    '</div>',
    '</section>',
  ].join('');

  return {
    path: opts.path,
    html: page({
      path: opts.path,
      title: opts.title,
      description: opts.description,
      onDark: true,
      noindex: opts.noindex,
      body,
      jsonLd: [breadcrumbJsonLd(crumbs)].concat(opts.jsonLd || []),
    }),
  };
}

export function aboutPage() {
  return prosePage({
    path: '/about/',
    crumb: 'About',
    h1: 'About TravelStoryMaker',
    lede: 'A small, independent library of travel writing, built to be read on a slow connection in a place you cannot pronounce.',
    title: 'About TravelStoryMaker - who we are and why this site exists',
    description: 'TravelStoryMaker is an independent, free library of travel stories, quotes and fun facts. Learn who writes it, how it is funded and how we check facts.',
    content: [
      '<h2>What this site is</h2>',
      '<p>TravelStoryMaker is a free reading library of <strong>' + COUNT_BY_TYPE.story + ' short travel stories</strong>, ' + COUNT_BY_TYPE.quote + ' quotes and proverbs, and ' + COUNT_BY_TYPE.fact + ' fun facts about places around the world, and it keeps growing. There is no account to create, no newsletter gate and no app to download. You open a page and you read.</p>',
      '<h2>Why it exists</h2>',
      '<p>Most travel content online is written for a search engine first and a human second: a thousand words of preamble before the one detail you came for. We wanted the opposite. Every entry here is between one and four sentences. You can read one in fifteen seconds, or three hundred in an afternoon.</p>',
      '<p>The second reason is speed. Travel writing is most useful when you are actually travelling, which is often exactly when your connection is worst. Every page on this site is a plain static HTML file with one stylesheet and one small script. No frameworks, no infinite scroll, no loading spinners.</p>',
      '<h2>Who writes it</h2>',
      '<p>TravelStoryMaker is written and edited by <strong>' + esc(AUTHOR.name) + '</strong>. The stories are written in-house, the fun facts are researched and written in-house, and the quotes belong to the people who said them and are attributed on every entry. There is no content agency involved and nothing here is published without a person reading it first.</p>',
      '<aside class="author-box" id="author">',
      '<img src="/assets/img/logo.svg" alt="" width="64" height="64" loading="lazy" decoding="async">',
      '<div><h3 style="margin-top:0">' + esc(AUTHOR.name) + '</h3>',
      '<p style="font-size:var(--fs-label);text-transform:uppercase;letter-spacing:.1em;font-weight:700;color:var(--text-faint)">' + esc(AUTHOR.role) + '</p>',
      '<p>' + esc(AUTHOR.bio) + '</p>',
      '<p><a href="/guides/">Read the guides</a> &middot; <a href="mailto:' + SITE.email + '">' + SITE.email + '</a></p></div>',
      '</aside>',
      '<h2>How we check things</h2>',
      '<p>Facts are checked against public reference sources: national statistics offices, UNESCO World Heritage listings, national park and government tourism authorities, university and museum publications, and established encyclopaedias. Where a figure is disputed or changes over time - a mountain height, a lake surface, a population - we say so rather than pretending to a precision that does not exist.</p>',
      '<p>Our full <a href="/editorial-policy/">editorial policy</a> explains how we handle sourcing, updates and corrections. If you find a mistake, <a href="/contact/">tell us</a> and include the entry number.</p>',
      '<h2>How it is funded</h2>',
      '<p>The site is free and funded by advertising, served through Google AdSense. We do not sell products, we do not run affiliate links inside the entries, and no advertiser has any say over what appears in the library. Advertising is clearly separated from the editorial content on every page.</p>',
      '<h2>What we do not do</h2>',
      '<ul>',
      '<li>We do not ask for your email address to let you read something.</li>',
      '<li>We do not publish sponsored entries dressed up as editorial.</li>',
      '<li>We do not generate entries in bulk and publish them unread.</li>',
      '<li>We do not track you across other websites for our own purposes.</li>',
      '</ul>',
      '<div class="callout"><p><strong>Want to get in touch?</strong> Corrections, suggestions, permissions and press enquiries all go to the same place: the <a href="/contact/">contact page</a>. If you have a travel story of your own, <a href="/submit/">send it to us</a> - we publish reader submissions.</p></div>',
      '<h2>Start reading</h2>',
      '<p>The complete library lives at <a href="/travelstories/">/travelstories</a>. If you would rather narrow it down first, try the <a href="/travelstories/stories/">stories</a>, the <a href="/travelstories/quotes/">quotes</a>, the <a href="/travelstories/fun-facts/">fun facts</a>, or pick a <a href="/destinations/">continent</a>.</p>',
    ].join(''),
    jsonLd: [{
      '@context': 'https://schema.org',
      '@type': 'AboutPage',
      name: 'About TravelStoryMaker',
      url: SITE.url + '/about/',
      publisher: { '@type': 'Organization', name: SITE.name, url: SITE.url + '/' },
    }, {
      '@context': 'https://schema.org',
      '@type': 'Person',
      '@id': AUTHOR.url,
      name: AUTHOR.name,
      jobTitle: AUTHOR.role,
      description: AUTHOR.bio,
      url: AUTHOR.url,
      email: 'mailto:' + SITE.email,
      worksFor: { '@type': 'Organization', name: SITE.name, url: SITE.url + '/' },
    }],
  });
}

export function contactPage() {
  return prosePage({
    path: '/contact/',
    crumb: 'Contact',
    h1: 'Contact us',
    lede: 'Corrections, permissions, advertising questions or just a fact we got wrong - this is where it goes.',
    title: 'Contact TravelStoryMaker',
    description: 'Get in touch with TravelStoryMaker about corrections, content permissions, advertising or privacy requests.',
    content: [
      '<h2>Email</h2>',
      '<p>The fastest way to reach us is by email:</p>',
      '<div class="callout"><p style="font-size:1.15rem"><strong><a href="mailto:' + SITE.email + '">' + SITE.email + '</a></strong></p><p>We read everything and reply to most things within a few working days.</p></div>',
      '<h2>What to include</h2>',
      '<ul>',
      '<li><strong>Corrections</strong> - the entry number (shown as #123 on each card), the page it appears on, and ideally a source we can check.</li>',
      '<li><strong>Permissions</strong> - which text you want to reuse, where, and whether it is commercial. See the <a href="/terms/">terms of use</a> first, because short quoted excerpts with a link back are already allowed.</li>',
      '<li><strong>Privacy requests</strong> - access, deletion or objection requests under GDPR, UK GDPR or CCPA. Put "Privacy request" in the subject line.</li>',
      '<li><strong>Advertising</strong> - we serve ads through Google AdSense and do not sell direct placements, but we are happy to answer questions.</li>',
      '<li><strong>Suggestions</strong> - a fact, a story or a quote you think belongs here. Tell us where it comes from.</li>',
      '</ul>',
      '<h2>Response times</h2>',
      '<p>We are a small team and this is not a 24-hour help desk. Confirmed factual errors are prioritised and usually corrected within a week. Everything else gets answered in the order it arrives.</p>',
      '<h2>Reporting a copyright concern</h2>',
      '<p>If you believe something on this site infringes your rights, email us with the exact URL, the entry number, a description of the work concerned and your contact details. We investigate every notice and remove material where a claim is substantiated.</p>',
      '<h2>Before you write</h2>',
      '<p>A quick look at the <a href="/faq/">FAQ</a> answers most questions about how the site works, where the content comes from and what you may reuse.</p>',
    ].join(''),
    jsonLd: [{
      '@context': 'https://schema.org',
      '@type': 'ContactPage',
      name: 'Contact TravelStoryMaker',
      url: SITE.url + '/contact/',
      mainEntity: { '@type': 'Organization', name: SITE.name, email: SITE.email, url: SITE.url + '/' },
    }],
  });
}

export function faqPage() {
  const extra = [
    { q: 'Do I need an account?', a: 'No. There is no account system on this site at all, and no login form to fill in.' },
    { q: 'Do you have a newsletter?', a: 'Not at the moment. If that changes, signing up will always be optional and never required to read anything.' },
    { q: 'Why do I see adverts?', a: 'Advertising pays the hosting bill and keeps the library free. Ads are served by Google AdSense and are always visually separated from editorial content.' },
    { q: 'Can I turn off personalised ads?', a: 'Yes. Visit Google Ad Settings to control ad personalisation, or use the consent controls shown in the European Economic Area, the UK and Switzerland. See the cookie policy for detail.' },
    { q: 'Is the site available offline?', a: 'Pages are lightweight enough that your browser will usually keep them cached, but there is no offline app. Saving a page from your browser works perfectly, because it is just HTML.' },
    { q: 'Can I translate the entries?', a: 'For non-commercial use, with attribution and a link back, yes. For anything commercial, ask first through the contact page.' },
    { q: 'How often is new content added?', a: 'The library is reviewed regularly. Corrections are applied as soon as they are confirmed, and entries are refreshed when facts change.' },
    { q: 'Who owns the copyright in the quotes?', a: 'The quotes belong to their authors and are reproduced as short attributed excerpts. Our own commentary, stories and fact write-ups are copyright TravelStoryMaker.' },
  ];
  const all = FAQS.concat(extra);
  return prosePage({
    path: '/faq/',
    crumb: 'FAQ',
    h1: 'Frequently asked questions',
    lede: 'How the site works, where the content comes from and what you are allowed to do with it.',
    title: 'FAQ - TravelStoryMaker',
    description: 'Answers about how TravelStoryMaker works, where our travel stories and fun facts come from, how the site is funded and what you may reuse.',
    content: all.map(function (f) {
      return '<details class="faq"><summary>' + esc(f.q) + '</summary><p>' + esc(f.a) + '</p></details>';
    }).join('') + '<p style="margin-top:28px">Still stuck? <a href="/contact/">Send us a message</a>.</p>',
    jsonLd: [{
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      mainEntity: all.map(function (f) {
        return { '@type': 'Question', name: f.q, acceptedAnswer: { '@type': 'Answer', text: f.a } };
      }),
    }],
  });
}

export function editorialPolicyPage() {
  return prosePage({
    path: '/editorial-policy/',
    crumb: 'Editorial policy',
    h1: 'Editorial policy',
    lede: 'How entries are researched, written, checked and corrected.',
    title: 'Editorial policy - TravelStoryMaker',
    description: 'How TravelStoryMaker researches, writes, verifies and corrects its travel stories, quotes and fun facts.',
    updated: true,
    content: [
      '<h2>Our standard</h2>',
      '<p>Every entry on this site is written by a person for people. We do not publish bulk-generated text, we do not spin articles from other websites, and we do not pad entries to hit a word count. An entry is as long as it needs to be, which is usually two sentences.</p>',
      '<h2>The three content types</h2>',
      '<h3>Fun facts</h3>',
      '<p>Fun facts are statements of verifiable information. Each one is checked against at least one authoritative public source before publication. Preferred sources are, in rough order: official government and statistical agencies, UNESCO and comparable international bodies, national park and heritage authorities, peer-reviewed research and university publications, major museums, and established reference encyclopaedias.</p>',
      '<p>Where a figure is genuinely disputed, changes over time, or depends on how something is measured, we flag that in the entry rather than picking the most impressive number. Mountain heights, lake areas, island counts and population figures are all examples where sources legitimately disagree.</p>',
      '<h3>Quotes</h3>',
      '<p>Quotes are reproduced as short excerpts with attribution to the person credited. Where a quote is widely circulated but the attribution is uncertain, we write "Attributed to" rather than asserting authorship. Proverbs and traditional sayings are labelled by culture or language of origin rather than given a false individual author.</p>',
      '<h3>Travel stories</h3>',
      '<p>Stories are short narrative pieces written to capture the texture of travel: the missed connection, the unexpected kindness, the local rule you only learn by breaking it. They are reading material rather than verified reportage, and they are not presented as news, reviews or factual claims about named businesses.</p>',
      '<h2>What we will not publish</h2>',
      '<ul>',
      '<li>Content copied or lightly reworded from another website.</li>',
      '<li>Bulk automated text published without human review.</li>',
      '<li>Sponsored material disguised as editorial.</li>',
      '<li>Facts we cannot trace to a credible source.</li>',
      '<li>Content that mocks, stereotypes or demeans the people who live in the places we write about.</li>',
      '</ul>',
      '<h2>Advertising and independence</h2>',
      '<p>The site is funded by advertising served through Google AdSense. Advertisers have no influence over editorial content, no advance sight of it and no right of veto. Ad units are visually distinct from entries and are never disguised as content. We do not place affiliate links inside entries.</p>',
      '<h2>Corrections</h2>',
      '<p>We would rather be corrected than be wrong. If you spot an error, send the entry number and, if you can, a source through the <a href="/contact/">contact page</a>. Confirmed factual errors are corrected promptly. Substantive changes to the meaning of an entry are noted rather than made silently.</p>',
      '<h2>Reviews and updates</h2>',
      '<p>The library is reviewed on a rolling basis. Entries that describe changing situations - retreating glaciers, shifting borders, shrinking lakes, revised measurements - are the first to be revisited.</p>',
      '<h2>Use of AI tools</h2>',
      '<p>We may use software tools to help with spelling, grammar and formatting, in the same way any writer uses a spellchecker. Editorial decisions, research, verification and the final text are the responsibility of a human editor, and no entry is published without human review.</p>',
    ].join(''),
  });
}

export function termsPage() {
  return prosePage({
    path: '/terms/',
    crumb: 'Terms of use',
    h1: 'Terms of use',
    lede: 'The rules for using this website. Short version: read anything, quote a little with a link, do not copy the lot.',
    title: 'Terms of Use - TravelStoryMaker',
    description: 'The terms governing use of the TravelStoryMaker website, including intellectual property, acceptable use, disclaimers and liability.',
    updated: true,
    content: [
      '<h2>1. Agreement</h2>',
      '<p>These terms of use govern your access to and use of ' + SITE.url + ' (the "Site"), operated by TravelStoryMaker ("we", "us", "our"). By accessing or using the Site you agree to these terms. If you do not agree with them, please stop using the Site.</p>',
      '<h2>2. What the Site provides</h2>',
      '<p>The Site is a free library of travel stories, quotes and fun facts published for general interest and entertainment. It is not a booking service, a travel agency, a tour operator or a source of professional advice. See our <a href="/disclaimer/">disclaimer</a> for the limits of what the content is intended to do.</p>',
      '<h2>3. Intellectual property</h2>',
      '<p>Unless stated otherwise, all text, layout, design, graphics, code and compilation on the Site are owned by us or licensed to us and are protected by copyright and other intellectual property laws. The arrangement and selection of the collection is itself protected as a compilation.</p>',
      '<p>Quotations reproduced on the Site remain the property of their respective authors or rights holders and are used as short attributed excerpts.</p>',
      '<h3>What you may do</h3>',
      '<ul>',
      '<li>Read, print and save pages for your own personal, non-commercial use.</li>',
      '<li>Quote a short extract (broadly, a single entry or less) provided you credit TravelStoryMaker and include a visible, followable link to the page it came from.</li>',
      '<li>Link to any page on the Site without asking permission.</li>',
      '</ul>',
      '<h3>What you may not do</h3>',
      '<ul>',
      '<li>Copy, republish or redistribute substantial parts of the collection, in any medium, without our written permission.</li>',
      '<li>Scrape, harvest or systematically extract content, including for the purpose of training machine learning models, without our written permission.</li>',
      '<li>Present our content as your own, or remove attribution and copyright notices.</li>',
      '<li>Frame the Site, or reproduce it in a way that suggests endorsement or partnership that does not exist.</li>',
      '<li>Use the Site for any unlawful purpose, or in a way that damages, disables or overburdens it.</li>',
      '<li>Attempt to gain unauthorised access to any part of the Site, its servers or any connected system.</li>',
      '</ul>',
      '<h2>4. Accuracy of content</h2>',
      '<p>We take care to research and check what we publish, and we correct errors when they are pointed out. Even so, the content is provided for general interest. Facts change, measurements are revised, borders move and opening hours are not our department. You should verify anything you intend to rely on, particularly anything relating to travel documents, safety, health or money.</p>',
      '<h2>5. Third-party links and advertising</h2>',
      '<p>The Site contains advertising served by third parties, principally Google AdSense, and may contain links to third-party websites. We do not control that material and are not responsible for its content, accuracy, products, services or privacy practices. A link or an advert is not an endorsement.</p>',
      '<h2>6. Availability</h2>',
      '<p>We aim to keep the Site available but do not guarantee uninterrupted access. We may change, suspend, restrict or withdraw any part of the Site at any time without notice, including individual entries or whole sections.</p>',
      '<h2>7. Disclaimer of warranties</h2>',
      '<p>The Site and its content are provided "as is" and "as available" without warranties of any kind, whether express or implied, including implied warranties of merchantability, fitness for a particular purpose, accuracy and non-infringement, to the fullest extent permitted by law.</p>',
      '<h2>8. Limitation of liability</h2>',
      '<p>To the fullest extent permitted by law, we shall not be liable for any indirect, incidental, special, consequential or punitive loss, or any loss of profit, revenue, data or goodwill, arising out of or in connection with your use of, or inability to use, the Site or anything you read on it. Nothing in these terms excludes or limits liability that cannot lawfully be excluded or limited.</p>',
      '<h2>9. Indemnity</h2>',
      '<p>You agree to indemnify and hold us harmless against any claim, loss, liability or expense arising from your breach of these terms or your misuse of the Site.</p>',
      '<h2>10. Privacy</h2>',
      '<p>Your use of the Site is also governed by our <a href="/privacy/">privacy policy</a> and <a href="/cookies/">cookie policy</a>, which form part of these terms.</p>',
      '<h2>11. Changes to these terms</h2>',
      '<p>We may update these terms from time to time. The version published on this page is the version in force, and the date at the top shows when it last changed. Continuing to use the Site after a change means you accept the revised terms.</p>',
      '<h2>12. Severability and waiver</h2>',
      '<p>If any provision of these terms is held to be invalid or unenforceable, the remaining provisions continue in full force. A failure to enforce any provision is not a waiver of it.</p>',
      '<h2>13. Governing law</h2>',
      '<p>These terms are governed by French law, and the courts of France shall have jurisdiction, without prejudice to any mandatory consumer protection rights available to you under the law of your country of residence.</p>',
      '<h2>14. Contact</h2>',
      '<p>Questions about these terms: <a href="mailto:' + SITE.email + '">' + SITE.email + '</a>, or use the <a href="/contact/">contact page</a>.</p>',
    ].join(''),
  });
}

export function privacyPage() {
  return prosePage({
    path: '/privacy/',
    crumb: 'Privacy policy',
    h1: 'Privacy policy',
    lede: 'What data this site collects, who processes it, and how to control or delete it.',
    title: 'Privacy Policy - TravelStoryMaker',
    description: 'How TravelStoryMaker handles personal data, cookies, advertising by Google AdSense, and your rights under GDPR and CCPA.',
    updated: true,
    content: [
      '<p>This policy explains how TravelStoryMaker ("we", "us") handles information when you visit ' + SITE.url + ' (the "Site"). We have tried to write it in plain language rather than legal fog.</p>',
      '<div class="callout"><p><strong>The short version.</strong> We do not ask you to create an account, we do not ask for your email to read anything, and we do not sell personal data. The Site is static. The data that is collected comes from our hosting provider\'s standard server logs and from Google, which serves the advertising that keeps the Site free.</p></div>',
      '<h2>1. Who is responsible</h2>',
      '<p>TravelStoryMaker is the data controller for this Site. You can reach us at <a href="mailto:' + SITE.email + '">' + SITE.email + '</a> or via the <a href="/contact/">contact page</a>.</p>',
      '<h2>2. What we collect</h2>',
      '<h3>a. Information you give us</h3>',
      '<p>If you email us, we receive whatever you put in the message: your email address, your name if you sign it, and the content of your enquiry. We use it only to answer you and we keep it no longer than needed for that purpose and any follow-up.</p>',
      '<h3>b. Information collected automatically</h3>',
      '<p>Like practically every website, our hosting provider records standard technical log data when a page is requested. That typically includes your IP address, the date and time, the page requested, the referring page, and your browser and operating system version. This is used for security, abuse prevention and aggregate traffic understanding.</p>',
      '<h3>c. Information collected by advertising partners</h3>',
      '<p>We display advertising through Google AdSense. Google and its partners may set and read cookies or similar identifiers on your device to serve and measure ads. See section 4.</p>',
      '<h3>d. Local storage</h3>',
      '<p>We store nothing of our own in your browser. The Site sets no cookies and writes no local storage values itself. Any cookie or identifier present will have been set by Google for advertising, as described in section 4.</p>',
      '<h2>3. Why we process data and on what legal basis</h2>',
      '<ul>',
      '<li><strong>To deliver the Site</strong> - necessary for the performance of providing the service you requested, and our legitimate interest in operating a working website.</li>',
      '<li><strong>To keep the Site secure</strong> - our legitimate interest in preventing abuse, fraud and attacks.</li>',
      '<li><strong>To answer your messages</strong> - our legitimate interest in responding to correspondence.</li>',
      '<li><strong>To show advertising</strong> - consent, where consent is required in your jurisdiction; otherwise our legitimate interest in funding free content. Non-personalised advertising may be shown where consent is refused.</li>',
      '</ul>',
      '<h2>4. Advertising and Google AdSense</h2>',
      '<p>This Site is funded by advertising served by Google AdSense (publisher ID pub-6636684537203477). You should know the following:</p>',
      '<ul>',
      '<li>Third-party vendors, including Google, use cookies to serve ads based on your prior visits to this and other websites.</li>',
      '<li>Google\'s use of advertising cookies enables it and its partners to serve ads to you based on your visit to this Site and other sites on the internet.</li>',
      '<li>You may opt out of personalised advertising by visiting <a href="https://www.google.com/settings/ads" rel="nofollow noopener" target="_blank">Google Ad Settings</a>.</li>',
      '<li>You can opt out of some third-party vendors\' use of cookies for personalised advertising at <a href="https://www.aboutads.info/choices/" rel="nofollow noopener" target="_blank">aboutads.info/choices</a> and <a href="https://www.youronlinechoices.eu/" rel="nofollow noopener" target="_blank">youronlinechoices.eu</a>.</li>',
      '<li>Google\'s own practices are described in the <a href="https://policies.google.com/technologies/partner-sites" rel="nofollow noopener" target="_blank">Google privacy and terms page for partner sites</a>.</li>',
      '</ul>',
      '<p>If you are in the European Economic Area, the United Kingdom or Switzerland, a consent message is presented before personalised advertising cookies are used, in line with Google\'s EU user consent policy. It is served by Google\'s certified consent management platform, and you can change your choice at any time by reopening that message.</p>',
      '<h2>5. What we do not do</h2>',
      '<ul>',
      '<li>We do not sell or rent personal data.</li>',
      '<li>We do not run an account system, so we hold no passwords.</li>',
      '<li>We do not knowingly collect data from children under 13, and the Site is not directed at children. If you believe a child has sent us personal data, contact us and we will delete it.</li>',
      '<li>We do not require any personal information in order to read the content.</li>',
      '</ul>',
      '<h2>6. Sharing</h2>',
      '<p>We share data only with the service providers necessary to run the Site: our hosting and content delivery provider, and Google for advertising. These providers process data on our behalf or, in Google\'s case, as an independent controller for advertising purposes. We may also disclose information where legally required, or to protect our rights, safety or property.</p>',
      '<h2>7. International transfers</h2>',
      '<p>Our providers may process data outside your country, including in the United States. Where personal data of EEA, UK or Swiss users is transferred, our providers rely on legal transfer mechanisms such as the European Commission\'s Standard Contractual Clauses or an adequacy decision.</p>',
      '<h2>8. Retention</h2>',
      '<p>Server logs are retained for a limited period by our hosting provider, typically measured in weeks, for security and diagnostics. Email correspondence is kept for as long as needed to deal with the matter and any reasonable follow-up. Advertising identifiers are retained according to Google\'s own retention policies.</p>',
      '<h2>9. Your rights</h2>',
      '<p>Depending on where you live, you may have the right to:</p>',
      '<ul>',
      '<li>access the personal data we hold about you;</li>',
      '<li>have inaccurate data corrected;</li>',
      '<li>have data erased;</li>',
      '<li>restrict or object to processing, including profiling for advertising;</li>',
      '<li>receive your data in a portable format;</li>',
      '<li>withdraw consent at any time, without affecting processing already carried out;</li>',
      '<li>opt out of the "sale" or "sharing" of personal information as those terms are defined under California law; and</li>',
      '<li>lodge a complaint with your data protection authority. In France this is the CNIL.</li>',
      '</ul>',
      '<p>To exercise any of these, email <a href="mailto:' + SITE.email + '">' + SITE.email + '</a> with "Privacy request" in the subject. We do not charge for this and we do not discriminate against anyone who exercises a right.</p>',
      '<h2>10. Do Not Track</h2>',
      '<p>The Site does not respond to Do Not Track browser signals, because no consistent industry standard for them exists. Global Privacy Control signals, where transmitted, are treated as an opt-out of sale or sharing where applicable law requires it.</p>',
      '<h2>11. Security</h2>',
      '<p>The Site is served over HTTPS. Because it is static and holds no user accounts or databases, the surface for a data breach is very small. No system is perfectly secure, and we cannot guarantee absolute security of information transmitted over the internet.</p>',
      '<h2>12. Changes</h2>',
      '<p>We may update this policy. The date at the top of the page shows the current version. Material changes will be made obvious on this page rather than slipped in quietly.</p>',
      '<h2>13. Contact</h2>',
      '<p>Questions, requests or complaints: <a href="mailto:' + SITE.email + '">' + SITE.email + '</a>. See also our <a href="/cookies/">cookie policy</a>.</p>',
    ].join(''),
  });
}

export function cookiesPage() {
  return prosePage({
    path: '/cookies/',
    crumb: 'Cookie policy',
    h1: 'Cookie policy',
    lede: 'What is stored on your device, by whom, and how to switch it off.',
    title: 'Cookie Policy - TravelStoryMaker',
    description: 'Which cookies and similar technologies TravelStoryMaker and its advertising partners use, and how to control or block them.',
    updated: true,
    content: [
      '<h2>What cookies are</h2>',
      '<p>A cookie is a small text file placed on your device by a website. Similar technologies include local storage, pixels and device identifiers. They are used to remember preferences, measure traffic and, in the case of advertising, to select which adverts you see.</p>',
      '<h2>Cookies this site sets itself</h2>',
      '<p>None. The Site is a set of static pages with no login and no shopping basket, and it sets no cookies and writes no local storage values of its own. Everything described below is set by Google.</p>',
      '<h2>Cookies set by third parties</h2>',
      '<h3>Google AdSense</h3>',
      '<p>Advertising keeps this site free. Google and its partners may set cookies and similar identifiers to:</p>',
      '<ul>',
      '<li>serve advertising, including personalised advertising where you have consented;</li>',
      '<li>limit how many times you see the same advert;</li>',
      '<li>measure whether adverts were viewed and whether they worked;</li>',
      '<li>detect and prevent advertising fraud and abuse.</li>',
      '</ul>',
      '<p>Common identifiers in this category include Google\'s DoubleClick cookie and the __gads and __gpi cookies. Their lifetimes and precise purposes are set by Google, not by us, and are described in <a href="https://policies.google.com/technologies/partner-sites" rel="nofollow noopener" target="_blank">Google\'s policy for partner sites</a>.</p>',
      '<h3>Fonts</h3>',
      '<p>Typefaces are served from this site\'s own domain, not from Google Fonts or any other font service. Loading a page therefore makes no request to a third-party font server and discloses your IP address to no one but our host and, if advertising is shown, Google.</p>',
      '<h2>Consent</h2>',
      '<p>If you are in the European Economic Area, the United Kingdom or Switzerland, a consent message is shown before advertising cookies that require consent are used. It is provided by Google\'s certified consent management platform. You can accept, refuse or change your preferences at any time by reopening that message. If you refuse, you will still see advertising, but it will be non-personalised - that is, based on the page you are reading rather than on a profile.</p>',
      '<h2>How to control cookies</h2>',
      '<ul>',
      '<li><strong>In your browser</strong> - every major browser lets you block or delete cookies, and offers a private browsing mode. Blocking all cookies may break parts of other websites, though it will not break this one.</li>',
      '<li><strong>Ad personalisation</strong> - <a href="https://www.google.com/settings/ads" rel="nofollow noopener" target="_blank">Google Ad Settings</a>.</li>',
      '<li><strong>Industry opt-outs</strong> - <a href="https://www.youronlinechoices.eu/" rel="nofollow noopener" target="_blank">Your Online Choices</a> (Europe) and <a href="https://www.aboutads.info/choices/" rel="nofollow noopener" target="_blank">the DAA opt-out</a> (United States).</li>',
      '<li><strong>Our own storage value</strong> - clear your browser\'s site data for this domain and it is gone.</li>',
      '</ul>',
      '<h2>Changes</h2>',
      '<p>If we add analytics or another third-party service, this page is updated before it goes live. The date at the top tells you when it last changed.</p>',
      '<h2>More detail</h2>',
      '<p>See our <a href="/privacy/">privacy policy</a> for the wider picture, or <a href="/contact/">get in touch</a> with a specific question.</p>',
    ].join(''),
  });
}

export function disclaimerPage() {
  return prosePage({
    path: '/disclaimer/',
    crumb: 'Disclaimer',
    h1: 'Disclaimer',
    lede: 'What this site is for, and what you should not rely on it for.',
    title: 'Disclaimer - TravelStoryMaker',
    description: 'The limits of the information published on TravelStoryMaker, including travel, safety, health and financial matters.',
    updated: true,
    content: [
      '<h2>General information only</h2>',
      '<p>Everything published on this Site is for general information and entertainment. It is written with care and checked before publication, but it is not professional advice and must not be treated as such.</p>',
      '<h2>Not travel, legal, medical or financial advice</h2>',
      '<p>Nothing here constitutes advice on visas, entry requirements, vaccinations, insurance, safety, security, currency, tax or the law of any country. Requirements change frequently and depend on your nationality, your route and the date you travel. Always check with the relevant embassy, your government\'s official travel advice and a qualified professional before making decisions.</p>',
      '<h2>Accuracy and currency</h2>',
      '<p>Facts age. Glaciers retreat, borders shift, lakes shrink, measurements get revised, and a museum that opened at nine last year may open at ten now. We correct errors as soon as they are confirmed, but we cannot warrant that every entry is complete, current or accurate at the moment you read it.</p>',
      '<h2>Stories are narrative</h2>',
      '<p>The travel stories on this Site are short narrative pieces intended to convey the feel of travelling. They are not reportage, not reviews, and not factual claims about identifiable individuals or named businesses. Any resemblance to a specific person is not intended as a statement of fact about them.</p>',
      '<h2>External links</h2>',
      '<p>We link to third-party websites where it is useful. We do not control them, we do not monitor them, and we are not responsible for their content, availability, accuracy or privacy practices. A link is not an endorsement.</p>',
      '<h2>Advertising</h2>',
      '<p>The Site displays advertising served by Google AdSense. We do not choose, review or endorse the individual adverts shown, and their appearance does not imply any relationship with the advertiser. Any dealings you have with an advertiser are between you and them.</p>',
      '<h2>Risk of travel</h2>',
      '<p>Travel involves risk, and some of the places described here involve altitude, wildlife, remote terrain, extreme temperatures or unstable conditions. Nothing on this Site is a recommendation to attempt anything beyond your competence, and you are responsible for your own safety and preparation.</p>',
      '<h2>Limitation of liability</h2>',
      '<p>To the fullest extent permitted by law, we accept no liability for any loss or damage arising from reliance on anything published on this Site. Your use of the Site is at your own risk and is governed by our <a href="/terms/">terms of use</a>.</p>',
      '<h2>Corrections</h2>',
      '<p>Found something wrong? Please <a href="/contact/">tell us</a> with the entry number. We would rather fix it than defend it.</p>',
    ].join(''),
  });
}

export function notFoundPage() {
  const body = [
    '<section class="hero">',
    '<div class="hero__blobs" aria-hidden="true"><span class="hero__blob hero__blob--a"></span><span class="hero__blob hero__blob--c"></span></div>',
    '<div class="container hero__inner center">',
    '<span class="eyebrow"><span class="dot"></span>Error 404</span>',
    '<h1>You have taken <br><span class="grad-text">a wrong turn</span></h1>',
    '<p class="hero__lede" style="margin-inline:auto">This page does not exist, which happens to the best of us. The good news is that the rest of the site does.</p>',
    '<div class="hero__cta" style="justify-content:center">',
    '<a class="btn btn--primary" href="/destinations/">Find a country</a>',
    '<a class="btn btn--ghost" href="/travelstories/">Read the library</a>',
    '</div>',
    '</div>',
    '</section>',
    '<section class="section">',
    '<div class="container center">',
    /*
     * There is no site-wide search to offer here - the search on a listing page only filters that
     * page - so the recovery route is by intent rather than a box that would not work. Four, not
     * six: a 404 is already a small failure, and a wall of equal options is not help.
     */
    '<h2 style="font-size:1.3rem">Were you looking for one of these?</h2>',
    '<div class="chips" style="justify-content:center">',
    '<a class="chip" href="/destinations/#by-country">A country</a>',
    '<a class="chip" href="/guides/">A travel guide</a>',
    '<a class="chip" href="/blog/">A trip itinerary</a>',
    '<a class="chip" href="/contact/">Tell us the link is broken</a>',
    '</div>',
    '</div>',
    '</section>',
  ].join('');

  return {
    path: '/404.html',
    html: page({
      path: '/404.html',
      title: 'Page not found - TravelStoryMaker',
      description: 'That page does not exist. Browse the library of travel stories, quotes and fun facts instead.',
      onDark: true,
      noindex: true,
      body,
    }),
  };
}
