import { page, esc, breadcrumbs, breadcrumbJsonLd, SITE, AUTHOR, SUBMIT_MAILTO } from '../layout.mjs';
import { heroBackdrop } from '../photos.mjs';
import { COUNT_BY_TYPE, ENTRIES } from '../data/index.mjs';

const EXAMPLE = ENTRIES.find(function (e) { return e.title === 'The barman who kept the light on'; }) || ENTRIES.find(function (e) { return e.type === 'story'; });
const EXAMPLE_WORDS = EXAMPLE.text.trim().split(/\s+/).length;
const EXAMPLE_PAGE = Math.ceil(EXAMPLE.id / 100);
const EXAMPLE_HREF = (EXAMPLE_PAGE === 1 ? '/travelstories/' : '/travelstories/page/' + EXAMPLE_PAGE + '/') + '#e' + EXAMPLE.id;

export function submitPage() {
  const crumbs = [{ href: '/', label: 'Home' }, { href: '/submit/', label: 'Propose a story' }];

  const body = [
    '<section class="hero hero--compact hero--photo">',
    heroBackdrop('stories'),
    '<div class="hero__blobs" aria-hidden="true"><span class="hero__blob hero__blob--a"></span><span class="hero__blob hero__blob--c"></span></div>',
    '<div class="container hero__inner">',
    breadcrumbs(crumbs),
    '<h1>Propose your <br><span class="grad-text">travel story</span></h1>',
    '<p class="hero__lede">Every one of the ' + COUNT_BY_TYPE.story + ' stories in this library started as something that actually happened to somebody. If you have one, we would like to read it.</p>',
    '<div class="hero__cta">',
    '<a class="btn btn--primary" href="' + SUBMIT_MAILTO + '">Send your story by email</a>',
    '<a class="btn btn--ghost" href="#what-works">What makes a good one</a>',
    '</div>',
    '</div>',
    '</section>',

    '<section class="section">',
    '<div class="container">',

    '<div class="section-head"><h2>How it works</h2></div>',
    '<div class="steps-grid">',
    '<div class="step-card"><span class="step-card__n">1</span><h3>Write it badly</h3><p>Three to six sentences, in whatever order it comes out. Do not polish it. We would rather have the real version than a tidy one.</p></div>',
    '<div class="step-card"><span class="step-card__n">2</span><h3>Email it</h3><p>Use the button above and the template fills itself in. No account, no form, no newsletter you did not ask for.</p></div>',
    '<div class="step-card"><span class="step-card__n">3</span><h3>We edit and publish</h3><p>We trim for length, keep your voice, and put it in the library under your name or anonymously — your choice.</p></div>',
    '</div>',

    '<div class="prose" style="margin-top:64px">',

    '<h2 id="what-works">What makes a story work here</h2>',
    '<p>The entries in this library are short on purpose — most are two to four sentences. What makes them worth reading is not scale or drama. It is a specific detail that could only have happened in that place, on that day, to you.</p>',
    '<p>The best submissions tend to have one of these:</p>',
    '<ul>',
    '<li><strong>An unexpected kindness.</strong> The barman who let us sleep on beer crates in Reykjavík. The bus driver in Snowdonia who saw two head torches on the mountain and refused to leave.</li>',
    '<li><strong>A local rule you only learned by breaking it.</strong> The tissue packet on a Singapore hawker table. The bread that is never placed upside down in Uzbekistan.</li>',
    '<li><strong>A plan that fell apart and turned into the trip.</strong> Missed ferries, cancelled flights, four days stranded by a typhoon in a fishing village.</li>',
    '<li><strong>A small ritual done properly.</strong> Three glasses of tea in the Sahara. A monk\'s alms round at six in the morning. A market that closes at noon whatever you want.</li>',
    '<li><strong>A moment with no photograph.</strong> Usually the best ones.</li>',
    '</ul>',

    '<h2>What to include when you write</h2>',
    '<ul>',
    '<li><strong>Where.</strong> Town and country, as precisely as you can remember.</li>',
    '<li><strong>Roughly when.</strong> A year or a season is enough; we do not publish exact dates.</li>',
    '<li><strong>The story itself.</strong> Three to six sentences. Longer is fine, we will trim it.</li>',
    '<li><strong>How to credit you.</strong> A first name, a full name, an initial, or anonymous. We will use exactly what you ask for.</li>',
    '</ul>',
    '<p>You do not need to write in perfect English. A large share of the people who read this site are not native speakers either, and we would rather have the story than the grammar.</p>',

    '<h2>What we cannot publish</h2>',
    '<ul>',
    '<li>Anything copied from another website, a book or someone else\'s post.</li>',
    '<li>Text generated by an AI tool and sent as your own experience. We read everything, and it shows.</li>',
    '<li>Complaints about a named hotel, restaurant, airline or individual. This is not a review site and we will not host claims we cannot verify.</li>',
    '<li>Anything that identifies a private person who has not agreed to it.</li>',
    '<li>Promotional content, or a story written to get a link to somewhere else.</li>',
    '<li>Content that mocks or stereotypes the people who live in the place you visited.</li>',
    '</ul>',

    '<h2>Your rights, in plain language</h2>',
    '<div class="callout">',
    '<p><strong>You keep the copyright in your story.</strong> By sending it you give us permission to edit it for length and clarity and to publish it free of charge on this site, with the credit you asked for.</p>',
    '<p>You can ask us to take it down at any time and we will, no explanation needed. We do not sell submissions, we do not pass your email address to anybody, and we will never add you to a mailing list. See the <a href="/privacy/">privacy policy</a> for what happens to the email itself.</p>',
    '<p>We do not pay for submissions. The site is free to read and funded by advertising, and we would rather be straightforward about that than imply otherwise.</p>',
    '</div>',

    '<h2>What happens next</h2>',
    '<p>Every submission is read by a person — usually ' + esc(AUTHOR.short) + '. If we publish it, you will get an email with the link and the entry number. If we do not, you will still get a reply, because sending someone your writing and hearing nothing back is a miserable experience.</p>',
    '<p>We are a small operation, so give it a couple of weeks. Published stories are checked against our <a href="/editorial-policy/">editorial policy</a> like everything else on the site.</p>',

    '<h2>An example of the right length</h2>',
    '<blockquote class="submission-example">',
    '<p>&ldquo;' + esc(EXAMPLE.text) + '&rdquo;</p>',
    '<cite><a href="' + EXAMPLE_HREF + '">Entry #' + EXAMPLE.id + '</a> &middot; ' + esc(EXAMPLE.place) + '</cite>',
    '</blockquote>',
    '<p>' + EXAMPLE_WORDS + ' words. That is the whole thing, and it is one of the most read entries on the site.</p>',

    '</div>',

    '<div class="submit-final">',
    '<h2>Ready?</h2>',
    '<p>The email template is already written. You just fill in the gaps.</p>',
    '<p><a class="btn btn--primary" href="' + SUBMIT_MAILTO + '">Propose your travel story</a></p>',
    '<p class="submit-final__note">Or write to <a href="mailto:' + SITE.email + '">' + SITE.email + '</a> however you like. There is no wrong format.</p>',
    '</div>',

    '</div>',
    '</section>',
  ].join('');

  return {
    path: '/submit/',
    html: page({
      path: '/submit/',
      title: 'Propose your travel story | TravelStoryMaker',
      description: 'Share a travel story that actually happened to you. A few sentences is enough: we edit for length, publish it free, and you keep the copyright.',
      onDark: true,
      body,
      jsonLd: [
        breadcrumbJsonLd(crumbs),
        {
          '@context': 'https://schema.org',
          '@type': 'WebPage',
          name: 'Propose your travel story',
          url: SITE.url + '/submit/',
          description: 'Submission guidelines for reader travel stories on TravelStoryMaker.',
          isPartOf: { '@type': 'WebSite', name: SITE.name, url: SITE.url + '/' },
        },
        {
          '@context': 'https://schema.org',
          '@type': 'HowTo',
          name: 'How to submit a travel story to TravelStoryMaker',
          description: 'Send a short true travel story by email and have it published free in the TravelStoryMaker library.',
          totalTime: 'PT10M',
          step: [
            { '@type': 'HowToStep', name: 'Write it badly', text: 'Write three to six sentences about what actually happened, without polishing it.' },
            { '@type': 'HowToStep', name: 'Email it', text: 'Send it to ' + SITE.email + ' with the place, roughly when it happened, and the name you want it published under.' },
            { '@type': 'HowToStep', name: 'We edit and publish', text: 'A human reads every submission, trims it for length, and publishes it in the library with your chosen credit.' },
          ],
        },
      ],
    }),
  };
}
