// Traveller fact sheet per country page, keyed by the slug used in src/countries.mjs.
// `flag` is a Wikimedia Commons file name; tools/fetch-assets.mjs downloads a small PNG of each.
export const COUNTRY_FACTS = {
  'united-states': {
    flag: 'Flag_of_the_United_States.svg',
    capital: 'Washington, D.C.',
    currency: 'US dollar (USD)',
    languages: 'English (no official language at federal level)',
    timezone: 'UTC−5 to UTC−10 across six zones',
    driving: 'Right',
    power: 'Type A / B, 120 V',
    climate: 'Everything. Subarctic in Alaska, desert in the Southwest, subtropical in Florida, temperate in the northeast.',
    bestTime: 'May–June and September–October for most of the country',
    note: 'Arizona does not observe daylight saving, but the Navajo Nation inside it does.',
  },
  australia: {
    flag: 'Flag_of_Australia.svg',
    capital: 'Canberra',
    currency: 'Australian dollar (AUD)',
    languages: 'English (de facto; no official language in law)',
    timezone: 'UTC+8 to UTC+11 across three main zones',
    driving: 'Left',
    power: 'Type I, 230 V',
    climate: 'Tropical and monsoonal in the north, arid through the centre, temperate in the southeast and southwest.',
    bestTime: 'September–November and March–May',
    note: 'Seasons are reversed. December is high summer and school holidays.',
  },
  japan: {
    flag: 'Flag_of_Japan.svg',
    capital: 'Tokyo',
    currency: 'Japanese yen (JPY)',
    languages: 'Japanese',
    timezone: 'UTC+9, no daylight saving',
    driving: 'Left',
    power: 'Type A / B, 100 V',
    climate: 'Humid subtropical over most of the country, cold and snowy in Hokkaido, a June–July rainy season almost everywhere.',
    bestTime: 'Late March–May and October–November',
    note: 'At 100 V, Japan has the lowest mains voltage in the world. Most modern chargers cope; hairdryers and kettles may not.',
  },
  india: {
    flag: 'Flag_of_India.svg',
    capital: 'New Delhi',
    currency: 'Indian rupee (INR)',
    languages: 'Hindi and English for official use; 22 scheduled languages',
    timezone: 'UTC+5:30, one zone for the whole country',
    driving: 'Left',
    power: 'Type C / D / M, 230 V',
    climate: 'Tropical in the south, temperate in the north, alpine in the Himalaya. The southwest monsoon runs roughly June–September.',
    bestTime: 'October–March',
    note: 'India recognises more than 120 languages with over 10,000 speakers each.',
  },
  canada: {
    flag: 'Flag_of_Canada_(Pantone).svg',
    capital: 'Ottawa',
    currency: 'Canadian dollar (CAD)',
    languages: 'English and French',
    timezone: 'UTC−3:30 to UTC−8 across six zones',
    driving: 'Right',
    power: 'Type A / B, 120 V',
    climate: 'Continental and cold over most of the country, milder on the Pacific coast, Arctic in the far north.',
    bestTime: 'June–September, or January–March for winter travel',
    note: 'Newfoundland runs half an hour offset from Atlantic time.',
  },
  'new-zealand': {
    flag: 'Flag_of_New_Zealand.svg',
    capital: 'Wellington',
    currency: 'New Zealand dollar (NZD)',
    languages: 'English, te reo Māori and New Zealand Sign Language',
    timezone: 'UTC+12 (UTC+13 in summer)',
    driving: 'Left',
    power: 'Type I, 230 V',
    climate: 'Temperate maritime. Wet on the west coast of the South Island, drier in the east, changeable everywhere.',
    bestTime: 'December–March, or October–November for fewer people',
    note: 'Biosecurity checks on arrival are strict. Declare all food, and clean your hiking boots before you fly.',
  },
  mexico: {
    flag: 'Flag_of_Mexico.svg',
    capital: 'Mexico City',
    currency: 'Mexican peso (MXN)',
    languages: 'Spanish de facto, alongside 68 recognised indigenous languages',
    timezone: 'UTC−6 to UTC−8',
    driving: 'Right',
    power: 'Type A / B, 127 V',
    climate: 'Tropical on both coasts, temperate on the central plateau, desert in the north. Rainy season roughly June–October.',
    bestTime: 'November–April',
    note: 'Mexico City sits at 2,240 m. Give yourself a day before doing anything strenuous.',
  },
  italy: {
    flag: 'Flag_of_Italy.svg',
    capital: 'Rome',
    currency: 'Euro (EUR)',
    languages: 'Italian',
    timezone: 'UTC+1 (UTC+2 in summer)',
    driving: 'Right',
    power: 'Type C / F / L, 230 V',
    climate: 'Mediterranean on the coasts, humid continental in the Po valley, alpine in the north.',
    bestTime: 'April–June and September–October',
    note: 'Historic centres are ringed by ZTL restricted-traffic zones enforced by camera. Fines arrive by post months later.',
  },
  peru: {
    flag: 'Flag_of_Peru.svg',
    capital: 'Lima',
    currency: 'Peruvian sol (PEN)',
    languages: 'Spanish, plus Quechua and Aymara where they are spoken',
    timezone: 'UTC−5, no daylight saving',
    driving: 'Right',
    power: 'Type A / B / C, 220 V',
    climate: 'Desert coast, high Andes, Amazon rainforest - three climates in one country. Andean dry season is May–September.',
    bestTime: 'May–September for the Andes',
    note: 'Cusco is at 3,400 m. Sleep low in the Sacred Valley first if you can.',
  },
  china: {
    flag: 'Flag_of_the_People\'s_Republic_of_China.svg',
    capital: 'Beijing',
    currency: 'Renminbi / yuan (CNY)',
    languages: 'Standard Mandarin',
    timezone: 'UTC+8 for the entire country',
    driving: 'Right',
    power: 'Type A / C / I, 220 V',
    climate: 'Subarctic in the northeast, subtropical in the south, arid in the west. Huge seasonal range.',
    bestTime: 'April–May and September–October',
    note: 'One time zone across a span that would naturally hold five: the sun rises after 10 am in western Xinjiang.',
  },
  morocco: {
    flag: 'Flag_of_Morocco.svg',
    capital: 'Rabat',
    currency: 'Moroccan dirham (MAD)',
    languages: 'Arabic and Amazigh (Berber); French widely used in business',
    timezone: 'UTC+1 year-round, moving to UTC±0 during Ramadan',
    driving: 'Right',
    power: 'Type C / E, 220 V',
    climate: 'Mediterranean on the north coast, Atlantic and mild on the west, arid inland, cold and snowy in the High Atlas.',
    bestTime: 'March–May and September–November',
    note: 'The dirham is a closed currency - you cannot buy it before you arrive and should spend it before you leave.',
  },
  brazil: {
    flag: 'Flag_of_Brazil.svg',
    capital: 'Brasília',
    currency: 'Brazilian real (BRL)',
    languages: 'Portuguese',
    timezone: 'UTC−2 to UTC−5',
    driving: 'Right',
    power: 'Type C / N, 127 V and 220 V depending on the region',
    climate: 'Equatorial in the Amazon, tropical along the coast, subtropical in the south.',
    bestTime: 'May–September for most regions',
    note: 'Voltage varies by city, and sometimes by socket within a hotel. Check the label before plugging anything in.',
  },
  spain: {
    flag: 'Flag_of_Spain.svg',
    capital: 'Madrid',
    currency: 'Euro (EUR)',
    languages: 'Spanish (Castilian); Catalan, Galician and Basque co-official regionally',
    timezone: 'UTC+1 (UTC+2 in summer); Canary Islands one hour behind',
    driving: 'Right',
    power: 'Type C / F, 230 V',
    climate: 'Mediterranean on the coast, continental on the central plateau with hot summers and cold winters, oceanic in the north.',
    bestTime: 'April–June and September–October',
    note: 'Lunch runs from two, dinner from nine. A restaurant serving dinner at seven is serving tourists.',
  },
  turkiye: {
    flag: 'Flag_of_Turkey.svg',
    capital: 'Ankara',
    currency: 'Turkish lira (TRY)',
    languages: 'Turkish',
    timezone: 'UTC+3 year-round, no daylight saving',
    driving: 'Right',
    power: 'Type C / F, 230 V',
    climate: 'Mediterranean on the south and west coasts, humid on the Black Sea, continental and harsh on the Anatolian plateau.',
    bestTime: 'April–June and September–October',
    note: 'Istanbul is the only major city built across two continents. The commuter ferry crosses between them.',
  },
  egypt: {
    flag: 'Flag_of_Egypt.svg',
    capital: 'Cairo',
    currency: 'Egyptian pound (EGP)',
    languages: 'Arabic',
    timezone: 'UTC+2 (UTC+3 in summer)',
    driving: 'Right',
    power: 'Type C / F, 220 V',
    climate: 'Hot desert almost everywhere, with a narrow Mediterranean strip on the north coast. Rain is close to nonexistent.',
    bestTime: 'October–April',
    note: 'Summer temperatures in Upper Egypt regularly exceed 40 °C. Sightseeing happens before ten in the morning.',
  },
  argentina: {
    flag: 'Flag_of_Argentina.svg',
    capital: 'Buenos Aires',
    currency: 'Argentine peso (ARS)',
    languages: 'Spanish (de facto)',
    timezone: 'UTC−3, no daylight saving',
    driving: 'Right',
    power: 'Type C / I, 220 V',
    climate: 'Subtropical in the north, temperate on the pampas, cold and windswept in Patagonia, alpine along the Andes.',
    bestTime: 'October–April for Patagonia, March–May for Buenos Aires',
    note: 'Aconcagua, at 6,961 m, is the highest peak outside Asia.',
  },
  greece: {
    flag: 'Flag_of_Greece.svg',
    capital: 'Athens',
    currency: 'Euro (EUR)',
    languages: 'Greek',
    timezone: 'UTC+2 (UTC+3 in summer)',
    driving: 'Right',
    power: 'Type C / F, 230 V',
    climate: 'Mediterranean: hot dry summers, mild wet winters. Mountains in the north get real snow.',
    bestTime: 'May–June and September–early October',
    note: 'The meltemi wind blows hard in July and August and cancels fast catamarans before it stops conventional ferries.',
  },
  england: {
    flag: 'Flag_of_England.svg',
    capital: 'London',
    currency: 'Pound sterling (GBP)',
    languages: 'English; Cornish recognised as a minority language',
    timezone: 'UTC±0 (UTC+1 in summer)',
    driving: 'Left',
    power: 'Type G, 230 V',
    climate: 'Temperate maritime. Mild, changeable, and wetter in the west than the east.',
    bestTime: 'May–September',
    note: 'England is one of the four nations of the United Kingdom, not a sovereign state in its own right.',
  },
  vietnam: {
    flag: 'Flag_of_Vietnam.svg',
    capital: 'Hanoi',
    currency: 'Vietnamese dong (VND)',
    languages: 'Vietnamese',
    timezone: 'UTC+7',
    driving: 'Right',
    power: 'Type A / C / F, 220 V',
    climate: 'Long enough to have three climates at once - a cool winter in the north, dry heat in the centre, tropical year-round in the south.',
    bestTime: 'Varies by region; February–April suits most of the country',
    note: 'The country is 1,650 km end to end. Check the forecast for the specific region, not for Vietnam.',
  },
  indonesia: {
    flag: 'Flag_of_Indonesia.svg',
    capital: 'Jakarta (Nusantara is being developed as the future capital)',
    currency: 'Indonesian rupiah (IDR)',
    languages: 'Indonesian; more than 700 local languages',
    timezone: 'UTC+7 to UTC+9 across three zones',
    driving: 'Left',
    power: 'Type C / F, 230 V',
    climate: 'Equatorial and humid all year. Wet season roughly November–March, dry April–October.',
    bestTime: 'May–September',
    note: 'Around 17,500 islands, roughly 6,000 of them inhabited. Distances between them are larger than the map suggests.',
  },
  colombia: {
    flag: 'Flag_of_Colombia.svg',
    capital: 'Bogotá',
    currency: 'Colombian peso (COP)',
    languages: 'Spanish; indigenous languages co-official in their territories',
    timezone: 'UTC−5, no daylight saving',
    driving: 'Right',
    power: 'Type A / B, 110 V',
    climate: 'Determined by altitude rather than season - hot on both coasts, spring-like in Medellín, cool in Bogotá at 2,640 m.',
    bestTime: 'December–March and July–August',
    note: 'The only South American country with coastline on both the Caribbean and the Pacific.',
  },
  norway: {
    flag: 'Flag_of_Norway.svg',
    capital: 'Oslo',
    currency: 'Norwegian krone (NOK)',
    languages: 'Norwegian (Bokmål and Nynorsk); Sami co-official in some municipalities',
    timezone: 'UTC+1 (UTC+2 in summer)',
    driving: 'Right',
    power: 'Type C / F, 230 V',
    climate: 'Milder than the latitude suggests thanks to the Gulf Stream. Wet on the west coast, colder and drier inland.',
    bestTime: 'June–August for the fjords, September–March for the aurora',
    note: 'Above the Arctic Circle the sun does not set for weeks in summer, and does not rise for weeks in winter.',
  },
  france: {
    flag: 'Flag_of_France.svg',
    capital: 'Paris',
    currency: 'Euro (EUR)',
    languages: 'French',
    timezone: 'UTC+1 in mainland France (UTC+2 in summer); twelve zones including overseas territories',
    driving: 'Right',
    power: 'Type C / E, 230 V',
    climate: 'Oceanic in the west, continental in the east, Mediterranean in the south, alpine in the mountains.',
    bestTime: 'May–June and September–October',
    note: 'Counting its overseas territories, France spans more time zones than any other country.',
  },
  portugal: {
    flag: 'Flag_of_Portugal.svg',
    capital: 'Lisbon',
    currency: 'Euro (EUR)',
    languages: 'Portuguese; Mirandese recognised regionally',
    timezone: 'UTC±0 (UTC+1 in summer); Azores one hour behind',
    driving: 'Right',
    power: 'Type C / F, 230 V',
    climate: 'Mediterranean with Atlantic influence. Mild wet winters, hot dry summers, cooler and greener in the north.',
    bestTime: 'March–June and September–October',
    note: 'Lisbon is built on seven steep hills. The funiculars and street lifts are public transport, not attractions.',
  },
  ethiopia: {
    flag: 'Flag_of_Ethiopia.svg',
    capital: 'Addis Ababa',
    currency: 'Ethiopian birr (ETB)',
    languages: 'Amharic, plus Afaan Oromo, Tigrinya, Somali and Afar as federal working languages',
    timezone: 'UTC+3',
    driving: 'Right',
    power: 'Type C / F / L, 220 V',
    climate: 'Temperate on the highlands where most people live, hot in the lowlands. Main rains June–September.',
    bestTime: 'October–March',
    note: 'Ethiopia keeps a 13-month calendar roughly seven years behind the Gregorian one, and the day starts at sunrise.',
  },
  namibia: {
    flag: 'Flag_of_Namibia.svg',
    capital: 'Windhoek',
    currency: 'Namibian dollar (NAD); South African rand also accepted',
    languages: 'English official; Afrikaans, German and Oshiwambo widely spoken',
    timezone: 'UTC+2',
    driving: 'Left',
    power: 'Type D / M, 220 V',
    climate: 'Desert and semi-desert. Hot days, cold nights, and one of the driest countries in sub-Saharan Africa.',
    bestTime: 'May–October',
    note: 'Distances are enormous and much of the road network is gravel. Check your rental agreement covers it.',
  },
  'south-africa': {
    flag: 'Flag_of_South_Africa.svg',
    capital: 'Pretoria (administrative), Cape Town (legislative), Bloemfontein (judicial)',
    currency: 'South African rand (ZAR)',
    languages: '12 official languages, including isiZulu, isiXhosa, Afrikaans, English and South African Sign Language',
    timezone: 'UTC+2',
    driving: 'Left',
    power: 'Type D / M / N, 230 V',
    climate: 'Mediterranean around Cape Town, subtropical on the east coast, dry and continental on the interior plateau.',
    bestTime: 'May–September for wildlife, November–March for the Cape',
    note: 'The Cape has a winter rainfall pattern and the rest of the country a summer one - they are opposite.',
  },
  ecuador: {
    flag: 'Flag_of_Ecuador.svg',
    capital: 'Quito',
    currency: 'US dollar (USD)',
    languages: 'Spanish, with Kichwa and Shuar official in intercultural contexts',
    timezone: 'UTC−5 on the mainland, UTC−6 in the Galápagos',
    driving: 'Right',
    power: 'Type A / B, 120 V',
    climate: 'Set by altitude, not season. Hot and humid on the coast and in the Amazon, spring-like in the highlands all year.',
    bestTime: 'June–September, and December–January in the highlands',
    note: 'Ecuador abandoned its own currency in 2000 and uses the US dollar, so bring small notes.',
  },
  bolivia: {
    flag: 'Flag_of_Bolivia.svg',
    capital: 'Sucre (constitutional), La Paz (seat of government)',
    currency: 'Boliviano (BOB)',
    languages: 'Spanish and 36 recognised indigenous languages',
    timezone: 'UTC−4, no daylight saving',
    driving: 'Right',
    power: 'Type A / C, 230 V',
    climate: 'Cold and thin on the altiplano, temperate in the valleys, tropical in the eastern lowlands.',
    bestTime: 'May–October, with the Uyuni mirror effect December–March',
    note: 'La Paz is the highest seat of government in the world. Altitude sickness is common and worth planning around.',
  },
  nepal: {
    flag: 'Flag_of_Nepal.svg',
    capital: 'Kathmandu',
    currency: 'Nepalese rupee (NPR)',
    languages: 'Nepali; more than 120 languages spoken',
    timezone: 'UTC+5:45',
    driving: 'Left',
    power: 'Type C / D / M, 230 V',
    climate: 'Subtropical in the Terai lowlands, temperate in the hills, alpine and arctic in the high Himalaya.',
    bestTime: 'October–November and March–April',
    note: 'One of only a handful of countries with a time zone offset by 45 minutes, and the only one with a non-rectangular flag.',
  },
  thailand: {
    flag: 'Flag_of_Thailand.svg',
    capital: 'Bangkok',
    currency: 'Thai baht (THB)',
    languages: 'Thai',
    timezone: 'UTC+7',
    driving: 'Left',
    power: 'Type A / B / C / O, 220 V',
    climate: 'Tropical. Cool and dry November–February, hot March–May, wet June–October - and the two coasts are offset.',
    bestTime: 'November–February',
    note: 'The Andaman and Gulf coasts have different monsoon timings, so one side is usually dry.',
  },
  philippines: {
    flag: 'Flag_of_the_Philippines.svg',
    capital: 'Manila',
    currency: 'Philippine peso (PHP)',
    languages: 'Filipino and English',
    timezone: 'UTC+8',
    driving: 'Right',
    power: 'Type A / B / C, 220 V',
    climate: 'Tropical maritime. Typhoon season runs roughly June–November, heaviest in the north and east.',
    bestTime: 'December–May',
    note: 'Sockets look American but carry 220 V. Plugging in a 110 V appliance without a converter will destroy it.',
  },
  tanzania: {
    flag: 'Flag_of_Tanzania.svg',
    capital: 'Dodoma (official); Dar es Salaam is the largest city',
    currency: 'Tanzanian shilling (TZS)',
    languages: 'Swahili and English',
    timezone: 'UTC+3',
    driving: 'Left',
    power: 'Type D / G, 230 V',
    climate: 'Tropical on the coast and Zanzibar, temperate on the highlands, cold on Kilimanjaro. Long rains March–May.',
    bestTime: 'June–October for wildlife, January–February for the calving season',
    note: 'Kilimanjaro summit night is below freezing even though you started the trek in shorts.',
  },
  mali: {
    flag: 'Flag_of_Mali.svg',
    capital: 'Bamako',
    currency: 'West African CFA franc (XOF)',
    languages: '13 national languages including Bambara are official; French is a working language',
    timezone: 'UTC±0',
    driving: 'Right',
    power: 'Type C / E, 220 V',
    climate: 'Sahelian and Saharan. Very hot, with a short rainy season roughly June–September in the south.',
    bestTime: 'November–February',
    note: 'Check your government\'s current travel advice before planning anything - large parts of the country are subject to warnings.',
  },
  chile: {
    flag: 'Flag_of_Chile.svg',
    capital: 'Santiago',
    currency: 'Chilean peso (CLP)',
    languages: 'Spanish',
    timezone: 'UTC−4 (UTC−3 in summer); Easter Island two hours behind',
    driving: 'Right',
    power: 'Type C / L, 220 V',
    climate: 'The driest desert on Earth in the north, Mediterranean in the centre, cold and wet in Patagonia.',
    bestTime: 'November–March for Patagonia, year-round for the Atacama',
    note: '4,300 km long and about 180 km wide. Two regions can be in opposite seasons on the same day.',
  },
  antarctica: {
    flag: null,
    capital: 'None - no government, no permanent population',
    currency: 'None; research stations use the currency of their supplying country',
    languages: 'None official; English, Spanish and Russian are common at stations',
    timezone: 'No official zone - stations use the time of their supply country',
    driving: 'Not applicable',
    power: 'Varies by station',
    climate: 'Polar desert. The largest desert on Earth, with almost no precipitation and winds over 300 km/h recorded.',
    bestTime: 'November–March, the only months tourist vessels operate',
    note: 'Governed by the Antarctic Treaty, which reserves the continent for peaceful scientific use.',
  },
};
